# Cheats
WAIT_TICK_COUNT = 25
HEAL_CHEAT = "healme"
HEAL_VALUE = 5
BIG_SPEED = "speedrun"
SPEED_VALUE = 5
GOD_MOD = "iamgod"
GOD_SPEED = 10
GOD_HP = 9999
GOD_COOL_DOWN = 5
BIG_FIRE_RATE = "pewpewpew"
COOL_DOWN_VALUE = 20

DEFAULT_GAME_FIELD_SIZE = (16 * 26, 16 * 26)

LITTLE_WALL_LENGTH = 16
BIG_WALL_LENGTH = LITTLE_WALL_LENGTH * 2

DEFAULT_BULLET_SIZE = (8, 8)
DEFAULT_EXPLOSION_LENGTH = 34
DEFAULT_BULLET_SPEED = 10

# TANKS
DEFAULT_TANK_SPAWNER_SIZE = (32, 32)
DEFAULT_TANK_SPAWNER_COOL_DOWN = 50
DEFAULT_TANK_SPAWNER_TANK_TO_GO = 4

PLAYER_TANK_HEALTH_POINTS = 10
PLAYER_TANK_SPEED = 2
PLAYER_TANK_COOL_DOWN = 50

DEFAULT_TANK_SIZE = (32, 32)
DEFAULT_TANK_SPEED = 2
DEFAULT_TANK_COOL_DOWN = 50
DEFAULT_TANK_HEALTH_POINTS = 1

ARMORED_BOT_SPEED = 1
ARMORED_TANK_SIZE = DEFAULT_TANK_SIZE
ARMORED_TANK_COOL_DOWN = 50
ARMORED_TANK_HEALTH_POINTS = 2

RAPID_FIRE_BOT_SPEED = 1
RAPID_FIRE_TANK_SIZE = DEFAULT_TANK_SIZE
RAPID_FIRE_TANK_COOL_DOWN = 20
RAPID_FIRE_TANK_HEALTH_POINTS = 1

HEAL_BOT_SPEED = 2
HEAL_TANK_SIZE = DEFAULT_TANK_SIZE
HEAL_TANK_COOL_DOWN = 50
HEAL_TANK_HEAL_COOL_DOWN = 150
HEAL_TANK_HEALTH_POINTS = 2

# WALLS
BRICK_HEALTH_POINTS = 1
IRON_HEALTH_POINTS = -1
BUSH_HEALTH_POINTS = -1
ASPHALT_HEALTH_POINTS = -1

FIRE_HEALTH_POINTS = -1
FIRE_DAMAGE_COOL_DOWN = 150
# FIRE_DAMAGE_COOL_DOWN = 30

DIRT_HEALTH_POINTS = -1
DIRT_SLOW_DAWN_COEFFICIENT = 2

# BONUS
BONUS_DURATION = 1000
ONLY_PLAYER_MODE = True
BONUS_HEAL_VALUE = 5
BONUS_COOL_DOWN = 1001
