[tool.coverage.run]
source = ["battle_city-py"]
omit = [
    "battle_city-py/enums/",
    "battle_city-py/buffers/",
    "battle_city-py/graphic_elements/",
    "battle_city/__main__.py",
    "battle_city/game_loop.py",
    "setup.py"
]

[tool.coverage.report]
show_missing = true
skip_covered = true
skip_empty = true
sort = "-Miss"
fail_under = 75

[tool.black]
line-length=79
target-version = ["py37"]
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
# add for black compatible, more info: https://black.readthedocs.io/en/stable/the_black_code_style.html
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true