[tool.coverage.run]
source = ["battle_city"]
omit = [
    "battle_city/enums.py",
    "battle_city/buffers/*",
    "battle_city/graphic_elements/*",
    "battle_city/game_logic_elements/game_constants.py",
    "battle_city/__main__.py",
    "battle_city/game_loop.py",
    "setup.py"
]

[tool.black]
line-length=79
target-version = ["py37"]
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
# add for black compatible, more info: https://black.readthedocs.io/en/stable/the_black_code_style.html
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true